name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: "~> v2"
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
